### ISSUE TITLE
UART support?

### ISSUE THREAD

**Issue by bm16ton** [daniel-thompson/i2c-star#16]
This is amazing had so much fun with it, im jealous of your skills! . unfortunately im still new and dumb to the programming side of things. I would love for my device to also be a usb2serial device as well as the i2c-star, havent used libopencm3, before I go down the rabbit hole on this figued i would ask what i was getting into. Arduino has libusbcomposite which makes that stuff super easy, any chance your ide has something like that?

**Comment by mucahitdemir** [comment]
You may need to look at this https://github.com/daniel-thompson/i2c-star

**Comment by daniel-thompson** [comment]
UART support is in the same category as SPI. See #5 .
