### ISSUE TITLE
[FR] Implement SPI also

### ISSUE THREAD

**Issue by ildar** [daniel-thompson/i2c-star#5]
Might also be possible?

**Comment by daniel-thompson** [comment]
It is possible, but the result would, for obvious reasons, no longer be "a compatible clone of Till Harbaum’s i2c-tiny-usb" so I have no plans to implement anything like this.

**Comment by ildar** [comment]
wait. I thought that the main point is the compatibility with Linux I2C
dev/ioctl. Linux now has SPI dev/ioctl also. Hence the question.

**Comment by daniel-thompson** [comment]
> wait. I thought that the main point is the compatibility with Linux I2C
> dev/ioctl. Linux now has SPI dev/ioctl also. Hence the question.

... and the answer: Yes, it is possible, but I have no plans to implement it.

Linux also has frameworks for GPIO, ADC, DAC, random numbers, CAN, PWM and UART. It is *possible* to implement a USB gadget based on an STM32 that implements all these things and more. It would probably be pretty cool... but it would also not be i2c-star any more.

**Comment by ildar** [comment]
yes, sure. Thanks.

**Comment by gdamjan** [comment]
if anyone ever decides to make spi support please write here :)
